### ISSUE TITLE
Touchspin + button isn't rendered with glyphicon

### ISSUE THREAD

**Issue by Bhoft** [kartik-v/yii2-widget-touchspin#10]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-widget-touchspin.
- [x] This is not an usage question. I confirm having read the [widget documentation and demos](http://demos.krajee.com/widget-details/touchspin).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] This is not a source plugin (touchspin) issue. (Those should be directed to the [plugin issues repo](https://github.com/touchspin/touchspin/search?q=&type=Issues)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.

## Steps to reproduce the issue
Set the 

        'verticalupclass' => 'glyphicon glyphicon-plus',
        'verticaldownclass' => 'glyphicon glyphicon-minus',

Also visible on the demos page for the button "Rating"
http://demos.krajee.com/widget-details/touchspin#advanced-usage

Setting the button texts works however

        'buttonup_txt' => '<i class="glyphicon glyphicon-plus"></i>',
        'buttondown_txt' => '<i class="glyphicon glyphicon-minus"></i>'

It also seems that the width of the input element isn't using the full column width any more (100% of e.g. col-md-9 with BS3) as with older versions.

## Expected behavior and actual behavior
![image](https://user-images.githubusercontent.com/1777147/45026549-f0403200-b03e-11e8-89f6-395f86fcfc7a.png)

I was expecting...
![image](https://user-images.githubusercontent.com/1777147/45026534-e3bbd980-b03e-11e8-9f5c-e4a3d50c0fd6.png)

The widget did work in version 1.2.1 but since 1.2.2 it doesn't (I also checked the dev version)

Sadly also the highlighting of errors or success validation doesn't look as good as with the older version.
older version:
![image](https://user-images.githubusercontent.com/1777147/45032559-6601c900-b052-11e8-940d-0c1c9d53a9f2.png)
![image](https://user-images.githubusercontent.com/1777147/45032705-c264e880-b052-11e8-855c-fe113ee8c116.png)

never version (without glyphicon):
![image](https://user-images.githubusercontent.com/1777147/45032645-9a758500-b052-11e8-8f2e-8ad6be2a7760.png)
![image](https://user-images.githubusercontent.com/1777147/45032683-b2e59f80-b052-11e8-8583-9b112bc06e38.png)

You see green borders on the right side when you have rounded corners.

I knew that the changes have something to do with the BS4 compatibility,

Browsers

- [ ] Google Chrome
- [x] Mozilla Firefox
- [x] Internet Explorer
- [ ] Safari

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:
- yii2-widget-touchspin version:

## Isolating the problem

- [x] This bug happens [on the widget demos page](http://demos.krajee.com/widget-details/touchspin)
- [x] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-widget-touchspin without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by Bhoft** [comment]
I see that you have changed your code for the rating button on your demo page.
From:

       'verticalupclass' => 'glyphicon glyphicon-plus',
       'verticaldownclass' => 'glyphicon glyphicon-minus',
to  use:

        'verticalup' => '<small><i class="glyphicon glyphicon-plus"></i></small>',
        'verticaldown' => '<small><i class="glyphicon glyphicon-minus"></i></small>'

instead. 

What is the reason behind to use different attributes? And not use the same 'button_up_txt' etc.?

    'verticalbuttons' => true,
    'buttonup_txt' => 'up',
    'buttondown_txt' => 'down',

I don't know if this is on purpose that you have `verticalup` and `buttonup_txt` in your javascript code.
But why don't you just use `settings.buttonup_txt` instead of `settings.verticalup` for the vertical buttons?

https://github.com/kartik-v/yii2-widget-touchspin/blob/34179c950c8ea83135ff6a73f6798e6ccfa5b6d3/src/assets/js/jquery.bootstrap-touchspin.js#L298
https://github.com/kartik-v/yii2-widget-touchspin/blob/34179c950c8ea83135ff6a73f6798e6ccfa5b6d3/src/assets/js/jquery.bootstrap-touchspin.js#L301

Otherwise you have to set two additional attributes if you enable the vertical buttons or wonder why the button texts are not used when you enable the vertical buttons mode.

I guess this is still a left after some changes or has this something to do if you want to render the buttons again after the browser size was changed and use the vertical buttons for a particular size and then use some other button texts as before?

**Comment by kartik-v** [comment]
Note that the source plugin code itself has been UPGRADED to latest version since the last release - and most of these changes are all to fit as per the modified code designed by the original plugin author. 

Few modifications to the CSS and JS have been added specifically by me to fit for the Yii2 BS3 and BS4 users. Will check your other feedback and see if there is anything else missed.

**Comment by Bhoft** [comment]
I knew that you aren't the author of the original plugin as you can't do everything :) 
But at least you try :+1: 

And of course to keep the plugin version up to date it is a requirement to use the original source. 
I haven't thought that this could be the issue.
