### ISSUE TITLE
Is there a way to configure a min value for this widget instead of 0?

### ISSUE THREAD

**Issue by fwroman** [kartik-v/yii2-widget-touchspin#5]
Hello I need to configure a default min value instead of 0 when I click minus button

Hope this can be possible, thanks...

**Comment by YasserHassan** [comment]
Old issue but since it's still open, you should be able to accomplish this using the plugin's own option via `pluginOptions` as follows:
```
'pluginOptions' => [
  'min' => 10, // Set this to the default value you want.
],
```
